server:
  port: 8081

spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: ${ACCOUNT_MONGODB_URI:mongodb://localhost:27017/accountdb}
      auto-index-creation: true

jwt:
  secret: 9a6e88a97f26414701ad41f0125e8b4e9e516f409f8756d123456789abcdef0123456789
  expiration-ms: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
